### ISSUE TITLE
Authentication: You do not have permission to access this pad

### ISSUE THREAD

**Issue by mooselumph** [citizenos/etherpad-lite-heroku#1]
I have this running on heroku at https://designcanvas.herokuapp.com/. Upon creating a new pad, I get the error "You do not have permission to access this pad."

I seem to get this error no matter what settings I have for requireAuthentication, requireAuthorization, or requireSession. Is there a simple configuration problem that I might be missing? 

After digging through the etherpad source code, I was about to simply throw in the towl, but I figured it was worth asking the question here. Thanks!

**Comment by tiblu** [comment]
@mooselumph Did you figure it out?

**Comment by mooselumph** [comment]
Not directly, no. I did figure out that I could circumvent the problem by creating public pads through the API. I'm sure this isn't an issue, per se. Probably just me not knowing what I'm doing!

**Comment by tiblu** [comment]
OK, if you still need some help with Etherpad, feel free to ping us.

**Comment by mooselumph** [comment]
Thanks, I appreciate it! Is opening an issue the best way to do that?

**Comment by tiblu** [comment]
@mooselumph If it's related to this project, then yes. Otherwise, you can contact us developer_AT_citizenos.com.
